name: recipe_web
description: My Recipes flutter app ported to Angular Dart.
version: 2.0.3
author: ppolasek <ppolasek@users.noreply.github.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  angular: "^5.0.0-beta"
  angular_forms: "^2.0.0-beta"
  angular_router: "^2.0.0-alpha+15"
#  angular_components: "^0.5.1"
  logging: "^0.11.3+1"
  http: "^0.11.0"
  stream_transform: "^0.0.6"
  
dev_dependencies:
  build_runner: "^0.9.0"
  build_test: "^0.10.2"
  build_web_compilers: "^0.4.0"
#  angular_test: "^1.0.0"
  test: "^1.0.0"

transformers:
